name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install wsinfer-zoo
        run: python -m pip install -e .[dev]
      - name: Check style (flake8)
        run: python -m flake8 wsinfer_zoo/
      - name: Check style (black)
        run: python -m black --check wsinfer_zoo/
      - name: Check types
        run: python -m mypy --install-types --non-interactive wsinfer_zoo/
      - name: Run the command line
        run: |
          wsinfer-zoo --help
          wsinfer-zoo ls
      - name: Attempt to download a model
        run: wsinfer-zoo get prostate-tumor-resnet34.tcga-prad
